server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  profiles:
    active: dev
  application:
    name: springboot-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # pool configuration
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      connectionProperties: druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=false
      filters: stat,wall,slf4j
      web-stat-filter: # WebStatFilter configuration
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet: # StatViewServlet configuration
        enabled: true
        url-pattern: /druid/*
        allow: 127.0.0.1
        deny: 192.168.1.73
        reset-enable: false
        login-username: admin
        login-password: abc123
      aop-patterns: com.springboot.demo.*
  data:
    mongodb:
      host: localhost
      port: 27017
      #username: root
      #password: mongo
      database: test
      #authentication-database: admin
  redis:
    lettuce:
      pool: 
        max-active: 8
        max-idle: 3
        min-idle: 1
        max-wait: 1000
      shutdown-timeout: 1000
    database: 0
    host: 127.0.0.1
    port: 6379
    password: abc123
    ssl: false
    timeout: 1000
    #cluster:
      #max-redirects: 5
      #nodes: 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003
  boot:
    admin:
      client:
        url: http://localhost:8080
#Spring Boot Actuator: -->  https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#production-ready
#/actuator/health
management:
  server:
    port: 8888 # should be protected after firewall
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
knife4j:
  basic: #非生产环境，可加权限校验
    enable: false
    username: x
    password: y
  production: false # 生产环境，直接关闭
---
spring:
  profiles: dev
logging:
  config: classpath:log/logback-dev.xml
---
spring:
  profiles: qa
logging:
  config: classpath:log/logback-qa.xml
---
spring:
  profiles: live
logging:
  config: classpath:log/logback-live.xml
---