server:
  port: 8081
spring:
  application:
    name: springboot-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariDataSource-Mysql-Pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    lettuce:
      pool: 
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
      shutdown-timeout: 1000
    database: 0
    host: 127.0.0.1
    port: 6379
    password: abc123
    ssl: false
    timeout: 1000
    #cluster:
      #max-redirects: 3
      #nodes: 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003
      #timeout: 5
      #password: abc123
    #sentinel:
      #master: 
      #nodes: 
  boot:
    admin:
      client:
        url: http://localhost:8080
#Spring Boot Actuator: -->  https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#production-ready
management:
  server:
    port: 9999 # should be protected after firewall
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always